version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  app-unsafe:
    build:
      context: .
      args:
        MAIN_CLASS: com.example.DistributedLock
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    command: ["${WORK_DURATION:-500}"]
    profiles: ["unsafe"]

  app-safe:
    build:
      context: .
      args:
        MAIN_CLASS: com.example.DistributedLockWithValueCheck
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    command: ["${WORK_DURATION:-500}"]
    profiles: ["safe"]

  app-toctou:
    build:
      context: .
      args:
        MAIN_CLASS: com.example.DistributedLockWithTOCTOU
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    command: ["${WORK_DURATION:-500}"]
    profiles: ["toctou"]

  app-lua:
    build:
      context: .
      args:
        MAIN_CLASS: com.example.DistributedLockWithLuaScript
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    command: ["${WORK_DURATION:-500}"]
    profiles: ["lua"]
