version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  redis-1:
    image: "redis:alpine"
    profiles: ["redlock"]
  redis-2:
    image: "redis:alpine"
    profiles: ["redlock"]
  redis-3:
    image: "redis:alpine"
    profiles: ["redlock"]
  redis-4:
    image: "redis:alpine"
    profiles: ["redlock"]
  redis-5:
    image: "redis:alpine"
    profiles: ["redlock"]

  app-unsafe:
    build:
      context: .
      args:
        MAIN_CLASS: com.example.DistributedLock
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    command: ["${WORK_DURATION:-500}"]
    profiles: ["unsafe"]

  app-safe:
    build:
      context: .
      args:
        MAIN_CLASS: com.example.DistributedLockWithValueCheck
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    command: ["${WORK_DURATION:-500}"]
    profiles: ["safe"]

  app-toctou:
    build:
      context: .
      args:
        MAIN_CLASS: com.example.DistributedLockWithTOCTOU
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    command: ["${WORK_DURATION:-500}"]
    profiles: ["toctou"]

  app-lua:
    build:
      context: .
      args:
        MAIN_CLASS: com.example.DistributedLockWithLuaScript
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - NUM_CONSUMERS=${NUM_CONSUMERS:-5}
    command: ["${WORK_DURATION:-500}"]
    profiles: ["lua"]

  app-redlock:
    build:
      context: .
      args:
        MAIN_CLASS: com.example.Redlock
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
    environment:
      - REDIS_NODES=redis-1:6379,redis-2:6379,redis-3:6379,redis-4:6379,redis-5:6379
      - NUM_CONSUMERS=${NUM_CONSUMERS:-5}
    command: ["${WORK_DURATION:-950}"]
    profiles: ["redlock"]
